version: '3'
services:

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: courseflow
      POSTGRES_USER: liushukov.kirill
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Zookeeper Service for Kafka
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  # Kafka Service
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

#  # Main Service
#  main:
#    image: kirinho/main-service:latest
#    container_name: main
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/courseflow?user=liushukov.kirill
#      SPRING_DATASOURCE_USERNAME: liushukov.kirill
#      SPRING_DATASOURCE_PASSWORD: 12345678
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - app-network
#
#  # Email Sender Service
#  emailSender:
#    image: kirinho/email-sender-service:latest
#    container_name: emailSender
#    ports:
#      - '8081:8081'
#    networks:
#      - app-network
#
#  # OAuth2 Service
#  oauth2:
#    image: kirinho/oauth2-service:latest
#    container_name: oauth2
#    ports:
#      - '8082:8082'
#    networks:
#      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

