version: '3'
services:

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: courseflow
      POSTGRES_USER: liushukov.kirill
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Zookeeper Service for Kafka
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: zookeeper
    ports:
      - '8088:8088'
    environment:
      ZOOKEEPER_CLIENT_PORT: 8088
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  # Kafka Service
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:8088
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  # Spring Boot Application (Optional)
  # spring-app:
  #   image: your-spring-boot-app-image
  #   container_name: spring-app
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/courseflow
  #     SPRING_DATASOURCE_USERNAME: liushukov.kirill
  #     SPRING_DATASOURCE_PASSWORD: 12345678
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #     SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #     SPRING_REDIS_HOST: redis  # Redis host
  #     SPRING_REDIS_PORT: 6379   # Redis port
  #   depends_on:
  #     - postgres
  #     - kafka
  #     - redis
  #   ports:
  #     - '8080:8080'  # Expose Spring Boot app on port 8080
  #   networks:
  #     - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
